### ISSUE TITLE
allow to clear a selection before a move is done

### ISSUE THREAD

**Issue by christiannagel** [CodebreakerApp/Codebreaker.Blazor#82]
click on a select that's not empty, clear the selection again

**Comment by christiannagel** [comment]
The layout doesn't match anymore with the reset button:

<img width="304" alt="image" src="https://github.com/user-attachments/assets/03467cfb-e7f4-4cda-84cc-11e929bbec9e">

**Comment by szv** [comment]
Layout issue solved in #105
